version: '3'
services:
  web:
    build: .
    command: ng serve -H 0.0.0.0
    volumes:
      - ./angular-tour-of-heroes:/angular-tour-of-heroes
      - /angular-tour-of-heroes/node_modules
    ports:
      - "4200:4200"
